### ISSUE TITLE
Metadata generation failed error when trying to install.

### ISSUE THREAD

**Issue by ghost** [irmen/cbmcodecs2#4]
When I'm trying to install this, Metadata generation failed popped up, any help is appreciated thanks. 
Image:
![image](https://user-images.githubusercontent.com/111659525/186991450-29666442-59e6-46ae-a5aa-becbd7e42f37.png)

**Comment by woodrowbarlow** [comment]
adding a bit more info: this occurs with python 3.10 on Windows only.

**Comment by irmen** [comment]
problem still occurs with python 3.11, and seems to be windows specific indeed;  installing on linux goes without errors.

**Comment by irmen** [comment]
fixed in just uploaded version 1.3 .
